### ISSUE TITLE
Need to update @solana/spl-token version 0.4.x

### ISSUE THREAD

**Issue by 0xlarry** [solana-developers/solana-actions#10]
We could not deploy our server to AWS due to conflicting dependencies...

we were depending on `@solana/spl-token@0.4.0`

`@solana/actions` depends on `@solana/spl-token@0.3.5`

we had to downgrade to `@solana/spl-token@0.3.5` in order to use @solana/actions

**Comment by nickfrosty** [comment]
the current version listed in the `@solana/actions` package is `"@solana/spl-token": "^0.3.5",`
with the `^` your desired version of `0.4.0` should work fine.

was there a specific error you were getting?

**Comment by nickfrosty** [comment]
I just realized that even though this package has the spl-token package installed, it is not actually using it....
I will clean up the dependencies :)

**Comment by nickfrosty** [comment]
This is now resolved with the latest update :)
