### ISSUE TITLE
Phantom says "Unable to simulate"

### ISSUE THREAD

**Issue by cyyyu** [solana-developers/solana-actions#30]
Hey first of all thanks for the awesome examples for solana actions. When I visit the transfer-sol example and try to scan the qrcode with phantom wallet, phantom says "Unable to simulate". I'm wondering what's the issue here and is there a way to work around?
![20D3577D-6A34-4993-B82B-928613C60F38_1_201_a](https://github.com/user-attachments/assets/283c2bea-fc37-43fd-a066-da91852a574f)

**Comment by nickfrosty** [comment]
the example code is on devnet, so your wallet must be selected to devnet

some wallets have issues performing full simulation on devnet

**Comment by cyyyu** [comment]
@nickfrosty In my application I've changed it to the mainnet and still got this issue.
