### ISSUE TITLE
redirect differently if the Blink is actually displayed

### ISSUE THREAD

**Issue by silto** [solana-developers/solana-actions#37]
Hello,

I am not sure this is the place to post this issue so don't hesitate to redirect me if I'm mistaken.

I would like to propose a little addition to the action/blink spec, that would probably be useful in a lot of use cases.

Right now, if I share a blink on X, the user will be redirected to a page when he clicks on it. The page is the actual link that was shared. The problem is that a lot of people don't have blinks activated yet, so it's useful to have an interstitial page that shows the same functionalities as the blink itself (like what dial.to does). But if the user has blinks activated, he will see the same thing twice when clicking on it, which doesn't make sense. So it would be a good idea to make it possible to redirect to a different page if the blink is shown or not.

So my proposal is this:
- add an optional `redirectUrl?: string` property to the GET response
- if it's present, redirect the user to that URL when the Blink is clicked (and display the domain of this URL on the blink instead of the blink URL's domain so there is no confusion)
- if it's not, redirect to the blink URL itself

This is not a breaking change, and it's fairly easy to implement for integrators.

Thank you for your time, I  hope I didn't waste your time and am available to discuss this if you want to.

**Comment by nickfrosty** [comment]
the correct place to propose new features and/or specification changes are the Solana Forums: https://forum.solana.com/c/srfc/6

but to respond to your idea here:

for non dial.to links, the website should be able to complete the same transaction flow that the blink provides. thats part of the point of blinks. you share a blink url. if the user has the ability to use blinks (i.e. have them enabled in the browser extension wallet or the website/platform/app supports blinks natively) then the user can immediately interact with the blink and get a transaction to sign. if they do not have them enabled or the website/app does not support them natively, the user can click the link to open the website and perform the same blink action to get a transaction to sign. the point is that they are the same functionality.

interstitial services (like dial.to) are a useful tool, but its better if developers/builders add the functionality to their own site therefore not needing an interstitial service.

take jupiter for example. you can share a link to any jup swap page as the blink url. if a user has a blink enabled client, they can interact with the blink and perform the token swap there. if they do not, they can simply click the link and go to the jup website and perform the token swap on the jup website. no interstitial website is needed.

if you want to enable this redirect capability, use your own site that you control. not an interstitial service

**Comment by nickfrosty** [comment]
closing since conversation should be shifted to the forum
